### ISSUE TITLE
Can't fetch library as a dependency

### ISSUE THREAD

**Issue by akadko** [guardianproject/AndroidPluggableTransports#16]
I'm trying to include APT in my project. But I'm getting a following error when declare dependency in recommended way:

ERROR: Failed to resolve: com.github.guardianproject:AndroidPluggableTransportsDispatcher:-SNAPSHOT

A log on jitpack.io shows that no build artifacts are found: https://jitpack.io/com/github/guardianproject/AndroidPluggableTransportsDispatcher/master-1.0.6-g8ed9eac-1/build.log

**Comment by ForsHant** [comment]
Yep, tested all of available libraries - none can be implemented in project

**Comment by n8fr8** [comment]
You need to use this gradle/maven repo: https://github.com/guardianproject/gpmaven

repositories {
	...
        maven { url "https://raw.githubusercontent.com/guardianproject/gpmaven/master" }
    }
